name: Check for New Releases

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 23 * * *'  # Every day at midnight

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "This is a test workflow."
