name: Start

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # Run daily, adjust as needed

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          ref: main
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/dsys1100/tg-autolspatch/actions/workflows/build-telegram.yml/dispatches \
            -d '{"ref":"main"}'
